### ISSUE TITLE
Misleading rep status for offline reps (not immediately known by MyNanoNinja?)

### ISSUE THREAD

**Issue by keerifox** [Nault/Nault#115]
![image](https://user-images.githubusercontent.com/29272208/89101600-ecff7d80-d3f0-11ea-83dc-f4dfb2cddea4.png)

choosing your own address as a representative tells you it's good until you refresh the page (which might be too late for people that decide it is a good idea but won't visit the wallet again in a while)

how do we proceed with this?

1a. there could be a neutral "Unknown Representative" status
1b. it could default to "Bad Representative" as we don't know anything about it
1c. re-fetch information in a couple seconds? [there should already be a style](https://i.imgur.com/dAdmgR1.png) for "Checking Representative..." somewhere in my commit history

2a. replace "It is highly advised to change..."  with "We were unable to determine the status of this representative."
2b. add an error "This representative was <b>never seen online</b>" or something along the lines

**Comment by BitDesert** [comment]
So this is only for a completely new rep that's not yet known on the network correct?
My Nano Ninja takes some time (up to an hour) to query for new representatives, so a refetch won't do anything.

The info gathered directly from the node is the primary source for rep data, so if the rep is already online and voting the status should be "OK". Otherwise you setup your own address by mistake or the rep is not online --> "Bad".
