### ISSUE TITLE
Accounts missing from dropdowns

### ISSUE THREAD

**Issue by keerifox** [Nault/Nault#135]
To reproduce visit the Send or Receive page directly (e.g. refresh after changing to Send/Receive pages)

![image](https://user-images.githubusercontent.com/29272208/89683420-0704f880-d8e8-11ea-8635-414bca0caad7.png)

![image](https://user-images.githubusercontent.com/29272208/89683503-2d2a9880-d8e8-11ea-8b9d-5dd7bfb08f49.png)

Similar with wallet sweeper

![image](https://user-images.githubusercontent.com/29272208/89683755-a6c28680-d8e8-11ea-9ac5-23f056a16711.png)

**Comment by Joohansson** [comment]
The problem only occurs on github pages because the routing is not working properly. The workaround for this was to include a 404.html page that saves the path https://github.com/Nault/Nault/blob/master/src/404.html and a redirect in the app component.

To fix the issue I moved the routing from the constructor down to the init where the wallet loading is happening. That way the dropdowns can be populated. Having it in the constructor will skip the init entirely (I think). There will be a slight delay where Nault first land on the home screen before going to the active screen but I don't know if it can be done better.

Verified working on send, receive, sweeper, representatives and settings page doing refresh.
![image](https://user-images.githubusercontent.com/2406720/89710138-c1e0d500-d980-11ea-96c6-001ac30dbaa4.png)
