### ISSUE TITLE
Wallet/Address Book Url Import doesn't work on nault.cc

### ISSUE THREAD

**Issue by keerifox** [Nault/Nault#153]
Settings -> Manage Wallet -> Export Nault Wallet -> Export QR Code

trying to visit that link gives an error

    Bad Import Data

    There was an issue reading the import data for your wallet. Double check the address and try again.

export as file seems to work fine

**Comment by keerifox** [comment]
seems that it works on localhost but not github pages hosted nault.cc
this also happens to the address book import

possibly the router is having issues obtaining the string after # (e.g. in the `/import-wallet#{base64}` endpoint)

**Comment by Joohansson** [comment]
I would guess it's the same problem as with all other routes when using github pages. We did a workaround by using a 404 page (https://github.com/Nault/Nault/blob/master/src/404.html) to save the route and then inject in the app component (https://github.com/Nault/Nault/blob/3802e912dca3105fa88cdc6c2f1a378e2ddf6480/src/app/app.component.ts#L85). Why that particular route does not work I don't know but I can investigate.

**Comment by BitDesert** [comment]
I might have an idea, other Angular implementations do that the same.
Just copy the index.html as the 404.html and let the application do the handling itself.

**Comment by Joohansson** [comment]
Fixed by
d7c567d
da8cfdb
da4bc63

Sorry about all commits but I couldn't figure out how to test this properly without pushing to the actual github pages. This also fixed other query params being part of the route, for example, if externally linking a remote offline procedure. Next will be to allow the wallet export QR to be read by the QR scanner.
