### ISSUE TITLE
Wording: BIP-39 Passphrase instead of password.

### ISSUE THREAD

**Issue by My1** [Nault/Nault#198]
Related to #194, #195 

The Standard uses the wording "passphrase"

https://github.com/bitcoin/bips/blob/master/bip-0039.mediawiki#From_mnemonic_to_seed

and as the wording of all the different secrets a user can get is already all over the place, let's not make it even worse.

as far as I have seen the term "password" is usually used to encrypt a wallet. be it of a companion wallet to secure privacy, or on a software wallet for the obvious reasons

**Comment by Joohansson** [comment]
Technically bip39 is using the wrong term. A password is a single word and probably what most people would use to encrypt the bip39 seed, while it can also be a passphrase if they like. The mnemonic is by definition a passphrase because it contains several words. But you're right, should keep the wordings as they are used elsewhere so I will go for what's being used here: t.ly/3rAw

Mnemonic Phrase (or just Mnemonic depending on where it's used) + Passphrase

**Comment by My1** [comment]
> A password is a single word and probably what most people would use to encrypt the bip39 seed, while it can also be a passphrase if they like

well it can be any string and general recommendation is not to use a single word. 

also the seed is not encrypted using the phrase, you instead throw the mnemnoic (also referred to as seed phrase or recoevery phrase) along with the Passphrase into a Key Derivation to get the BIP32 seed out.

for encryption tho software wallets often have a password, but that works obviously entirely different.

while in terms of how it's build the seed phrase is a passphrase, a password or -phrase is something at least I consider in the something you know category. while the seed generally isnt knowledge, also since you dont make it up, but is randomly generated and a direct representation of entropy.
