### ISSUE TITLE
macOS notarization?

### ISSUE THREAD

**Issue by rui-cruz** [Nault/Nault#244]
Hi, just to check.. did you forgot to notarize the app? or you don't even have an apple developer certificate?

![image](https://user-images.githubusercontent.com/1080374/103719732-90b51100-4fc1-11eb-98c3-92faa44118d6.png)

I was just trying to move my nanos to my ledger, but having troubles... this don't give me a lot confidence to allow this app to connect to my ledger, and I'm a dev.. imagine a regular folk..

**Comment by My1** [comment]
why should an open source dev with likely no real income off of this project pay a yearly fee that especially in corona time is not insignificant just so mac get get a stick out of its behind?
The Problem is clearly apple, not Nault.
also there's the web edition too.

**Comment by Joohansson** [comment]
We don't have an Apple cert. If you are familiar with how the Ledger device works, this should be of zero concern. I can understand this implies less confidence but as My1 said, Nault is not profitable or a company so it likely won't happen.

**Comment by My1** [comment]
also just for comparisons in windows it warns about downloaded apps no matter whether they codesigned it (but they change the wording and display of it, but dont change the actual interaction), Also on Windows there is no need to actually get your code signed by microsoft but by one of several trusted CAs, many of which have cheaper options than an apple dev account, which is why some open source projects like 7 zip may have a code signing for windows active.

I personally think this is an apple problem and I wouldnt be surprised if sooner or later it's gonna be appstore only.
