### ISSUE TITLE
Balance/tx list in account details not updating immediately after a receive

### ISSUE THREAD

**Issue by keerifox** [Nault/Nault#307]

**Comment by keerifox** [comment]
Suggested solution:

\- reload all account information when a new block is added to the account's chain (user needs to see the new balance, updated incoming tx and updated account tx list)

\- reload ONLY the incoming transactions list (& incoming balance label) when a new incoming transaction is observed

**Comment by Joohansson** [comment]
I think this is by design because reloading the detail page is a very heavy RPC call. Especially if having a lot of pending/history. Assume the account is receiving 10 transactions per second, it has to call the whole history 10 times per second. Also wasting the user's IP rate limiter.

If this is done it should include:
* Not updated often than 1/sec (but if it's skipping one call and it happens to be the final call, it must call it anyway. I think we had a similar logic somewhere, probably with the password bruteforce protection)
* Only effective for Nault account (no external accounts), but that's probably automatic since the websocket only subscribe to own account plus tracked watch-only accounts
* Respect min threshold set in the setting (probably automatic as well)

**Comment by keerifox** [comment]
yes it could be throttled to one `account_info` and `account_history` request per 3 seconds or so (if none requests were done within these past 3 seconds then there must not be any delay)
