### ISSUE TITLE
Javascript error when closing application

### ISSUE THREAD

**Issue by Jordan01010** [Nault/Nault#335]
![image](https://user-images.githubusercontent.com/59896821/109063390-ffb90700-76e0-11eb-9cd2-0667f1bcc701.png)

**Comment by BitDesert** [comment]
Can you reproduce the problem?

**Comment by m1k3s0** [comment]
I also get this on MacOS when closing the window.

<img width="251" alt="Screen Shot 2021-02-26 at 7 34 29 AM" src="https://user-images.githubusercontent.com/44042865/109302829-d0e98080-7807-11eb-858b-42da9f1ca07f.png">

**Comment by Jordan01010** [comment]
It seems to occur randomly I've only had this error since 1.10.1.

**Comment by Joohansson** [comment]
I'm not able to provoke this but not much was added in 1.10.1 so I think it could be related to this windows.onClose event that trigger a state save of the window size. I can try remove that in the next version because it's not needed anyway.

https://github.com/Nault/Nault/blob/v1.10.1/desktop-app/src/desktop-app.ts#L83

**Comment by Joohansson** [comment]
@JordanFerguson @m1k3io Please try release 1.10.2 and see if you can provoke this error

**Comment by m1k3s0** [comment]
> @JordanFerguson @m1k3io Please try release 1.10.2 and see if you can provoke this error

That solved the issue for me, thanks! 😃
