### ISSUE TITLE
Integrate with NanoMemo

### ISSUE THREAD

**Issue by fallerOfFalls** [Nault/Nault#365]
[NanoMemo](https://nanomemo.cc/) is the service I've been waiting for someone to build.

Can it be integrated into Nault? So we can add signed and (optionally, but by default) encrypted memos to our transactions. And display memos both from the blocks in our own chain, and any memos on the corresponding send/receive block on another chain?

I've made a similar request for [Natrium](https://github.com/appditto/natrium_wallet_flutter/issues/7).

**Comment by Joohansson** [comment]
If I understand correctly, such integration would depend on a third-party service? So if that server goes down, the memo is gone? Also looks like it won't be a free service, so who will pay for the API? https://nanomemo.cc/api
Or maybe show an error if the daily limit is reached. Since it requires an API key and not IP based, 100 would be for ALL Nault users which would run out quickly.

**Comment by fallerOfFalls** [comment]
>If I understand correctly, such integration would depend on a third-party service? So if that server goes down, the memo is gone?

Discussed [here](https://nanomemo.cc/docs#is-nanomemo-decentralized). I would prefer a distributed, decentralised database. But no one has built one. This seems like [a step along the way](https://www.reddit.com/r/nanocurrency/comments/bdecx6/development_inspiration_post_reviving_old/ekyqpk7/).

>Also looks like it won't be a free service, so who will pay for the API?

Could each user have their own API key? If not, could it be a premium feature?

>100 would be for ALL Nault users which would run out quickly.

Yeah, I don't think that option was intended for wallet maintainers!

This is the one for you:
>**Extra**
>TBD / request
>For services that might need more than the alloted daily credits, contact us with your request and we will hopefully work out a plan.

**Comment by Joohansson** [comment]
I don't think Nault can ever have premium features since it's a decentralized free wallet with no "company" hosting it. For premium feature to work there has to be an account that holds funds along with a database that acts as a bridge for the features customer pays for. And probably some support channel if something goes wrong. That is a no go for Nault as far as I understand as it requires some form of responsibility and maintenance.

**Comment by pawapps** [comment]
@fallerOfFalls thanks for creating this issue to discuss

@Joohansson happy to discuss potential implementations with Nault. I am able to provide a "higher limit" API key, but as you are serverless, I don't think that will help. I limit by reCAPTCHA [here](https://nanomemo.cc/write) to an endpoint (undocumented) that doesn't require an API key. I doubt that's an option as reCAPTCHA doesn't fit your UX/workflow. In this serverless space I'm seeing the benefits of IP limiting and I think that's reasonable from my side.

Initial thinking is IP limiting 10/day with inputs in "App Settings" for an API key pair.

Thoughts?

**Comment by Joohansson** [comment]
@pawapps I think that is a valid approach. Could have a link in the app settings for where to acquire this API key. Not sure yet how and where to integrate this UX wise but if the API limits can be solved like that (requests per IP per day), then we at least have a way forward. If the IP limit is reached, we could just display a warning, or maybe even tell the user how many memos he has left if that is sent along with the request.

For example, with my backend, I limit requests per IP per day and send back the remaining number both via the RPC command but also in the request header itself.

The Nault team has yet to decide if we want to integrate this, so can't promise yet.

**Comment by Joohansson** [comment]
We decided not to introduce yet another dependency at this time. Too much risk of it failing and don't want people to start rely on it. On-chain or at least decentralized/unlimited would have been another deal. You are free to ask again in the future!
