### ISSUE TITLE
Watch-only mode

### ISSUE THREAD

**Issue by fallerOfFalls** [Nault/Nault#374]
With remote signing, there's no way to see all your accounts, with their balances, and fiat conversions (and the total balance), because the device with the wallet isn't connected to the internet!

Could an option be added when setting up a wallet: **watch-only mode**. In this mode you have to manually input all addresses (since there's no seed from which to derive them).

**Comment by Joohansson** [comment]
I can investigate how much work this would be. A separate mode sounds like quite a bit of work to adapt all functions since most of the wallet features would not be working and has to be disabled. And the wallet is typically saved by used the seed so not sure how to even store the accounts. That would have to be adapted too.

A workaround for watch-only accounts is to save the account detail page as bookmarks in the browser. Or store them in the address book if you already have a wallet set up. For quick access.

**Comment by fallerOfFalls** [comment]
I have been using the address book workaround.

I can't see at a glance, which accounts currently have nano in and how much. And there's also no total balance.

**Comment by aleksre** [comment]
What about if it was possible to add any account to your wallet as a watchable/read-only account from the account explorer and have it show up in your account list? Obviously with some kind of indication that it's watch only. Not sure if this should affect total balance or not though, since there are use cases where this might not be desirable.

It would also be nice if these accounts could then show up in the receive dropdown. It should still be possible to receive transactions to accounts you don't have the keys for. Typical use case would be to receive to offline/paper wallet, or using Nault as a POS device without keys stored on the device.

**Comment by Joohansson** [comment]
@aleksre This is an interesting approach. Sounds a lot easier to implement too. Regarding balance, it could be a checkbox next to each watch-only account if it should be included in the total balance, OR one checkbox in the balance panel that would add ALL watch-only to the balance. It makes more sense the more I think about it because then you don't need to reset your normal wallet to add watch-only accounts. Always available and can be used for offline signing as well.

**Comment by fallerOfFalls** [comment]
This sounds even better.

Ideally it would work even when there is no wallet configured. Otherwise the use for offline signing would be a bit clunky.

**Comment by Joohansson** [comment]
@fallerOfFalls Good point. It would have to be stored in some separate local storage array that is cleared when you reset the wallet or empty the cache.

**Comment by fallerOfFalls** [comment]
would it be stored in the wallet if a wallet is configured? And only stored separately if no wallet is configured?

I'm thinking about how the list of watch-only accounts could be backed up.

**Comment by Joohansson** [comment]
Working on this now. It will be a compromise utilizing the address book to track balances and transactions (optionally per address), resulting in the lowest risk for mistaking them for regular accounts but flexible enough (with or without a wallet set up). The address book can also be exported/imported/bookmarked.

**Comment by fallerOfFalls** [comment]
Oh yeah! That sounds like a perfect approach actually (not sure why we didn't think of it).
