### ISSUE TITLE
Offline wallet functionality

### ISSUE THREAD

**Issue by BitDesert** [Nault/Nault#40]
It would be cool to run Nault on a PC without a internet connection and show the signed block instead of seding it directly to the node. The current implementations require building your block manually.

https://tools.nanos.cc/?tool=sign&type=0&address=&link=&previous=&rep=&balance=&amount=&amounttype=0
https://nanoo.tools/block

**Comment by Joohansson** [comment]
How do you envision this to work @BitDesert ? Like having your seed only offline and when doing a send it will display a big QR that you can scan with an online "empty" nault using the QR-reader and it will publish the block? Then the same for receive. But the reason it's so complicated in Keytools is because you can't only be offline. You need to have the frontier hash and latest balance which can only be retrieved from the network.

So Nault must communicate back and forth between online and offline, but only offline having the seed. I think it would have to be a special offline-signing tool or perhaps part of the "watch-only" account AKA account detail view.

For example in the following view (imagine this is your online account you want to send from)
https://nault.cc/account/nano_1wntkxqp5qnwzmqfgpn7zh4hkmj7sjgtp6w3n74wqgqnex3as8iz6phd6ydh

![image](https://user-images.githubusercontent.com/2406720/87314218-357af800-c523-11ea-81e6-fe6ea0e17a2b.png)

1. You press the imaginary button "Send Offline". Then you proceed with the send screen as usual but after you have put in the receiver and amount it display a QR code.
2. In the offline Nault: Scan QR and it will automatically sign using the current wallet and display another QR containing the signed block (with or without work)
3. In the online Nault: Scan QR and it will automatically publish the block (after doing work if work is missing)

For receive: Press "Receive Offline". The online Nault would ask you to pick one of the pending transactions and display a QR that needs to be signed. Then do 2 and 3 above but for receiving instead. Alternatively, there would exist a "receive offline" button for every pending transaction in the account detail view.

**Comment by BitDesert** [comment]
I think this could work...
But can you open Nault on the offline PC without any issues? Otherwise a seperate app that does this would be cool. Is there any standard, that app might be working with different wallets as well.

**Comment by Joohansson** [comment]
It will probably complain the node is offline but maybe can make a setting for offline mode. There is no standard so lets make one! The things that are sent via QR are just a block hash and signature but the hash has the same length as the seed so if we want to differentiate those we should maybe add some extra. The current standard covers nanoseed, nanokey and nanoblock. So if we just use nanohash and nanosignature I'm sure NF would add those to the doc. Btw we should add nanoseed to be detected by the QR reader if anyone usees that. Tix wallet does.
https://docs.nano.org/integration-guides/the-basics/#uri-and-qr-code-standards

I can later make the offline signing in Nault compatible with Keytools as well. 

But if you don't have any more clever ideas how to implement this then maybe I start some experimenting with it. It would be unique for any current wallet to have this solved.
