### ISSUE TITLE
Adressbook can be changed without unlocking wallet

### ISSUE THREAD

**Issue by Behind100proxies** [Nault/Nault#411]
In nault and vault you can freely change a saved adress in the adress book without unlocking the wallet.
If someone has access to your device this would mean they could just change one of your saved addresses and you would probably find out after you sent your coins.

**Comment by Joohansson** [comment]
That's a good point but the problem is you can add watch-only accounts to the address book without even having a wallet (password) set up. It was meant to be shared between wallets ie seed, private keys or ledger import. Clearing the wallet should not clear the address book because it's not saved with the seed. So I'm not sure how to solve that actually.

**Comment by filipesmedeiros** [comment]
It probably means there should be (at least) a locally stored pin/password to do stuff like this. Even if some people are tech savy enough, you still cut a few people off. Maybe encrypt it somehow?

**Comment by Joohansson** [comment]
Maybe it could work if an option to encrypt the address book completely separate from the wallet password. Downside would be it would not automatically unlock when you unlock the wallet. Would also need to be encrypted in the local storage and when exporting it to a file.

**Comment by filipesmedeiros** [comment]
How would you encrypt it client side?

**Comment by Joohansson** [comment]
> How would you encrypt it client side?

Same as the seed is encrypted. Using a user password and stored in browser local storage

**Comment by filipesmedeiros** [comment]
Nice. But doesn't that mean you can unlock everything at once? When you unlock the wallet (the actual seed) you also unlock the private key.

I use Nault with a Ledger so I'm not completely in on how it works with the password. Btw how would this work for Ledger users? A separate password?

**Comment by Joohansson** [comment]
No, you can't unlock everything at once, it's not that simple. The seed is encrypted with a password and is used to derive the private keys. That's one thing. But when you import another seed, private key or mnemonic the address book is still saved separately so you don't lose all your addresses. However, the password is changed when you set up a new wallet. Let's say you change the password, how would it then decrypt the address book and encrypt with the new password? It would have to first ask the user about the old password. That's terrible UX. But the real issue is when you use a Ledger that doesn't even have a wallet password. How to decrypt/encrypt the address book then? Or when you set up an address book full of watch-only accounts without even having a Nault wallet, again, no password.

There are only 4 outcomes of this as I see it:

1. Make the address book reset each time you reset the wallet. Disallow using address book when not having a wallet, or when using the Ledger (terrible solution and no more watch-only accounts that was just implemented)
2. Encrypt the address book separately using whatever password (could be the same as the wallet) but the wallet can only unlock both at the same time if the user chose to use the same password. Then you can have an encrypted address book also when using the Ledger or when not having a wallet, or when switching between wallets. You know Nault can export/import the wallet as a file which is very nice when you have several (still only one address book). This means the user needs to unlock two different things, possibly keeping track of two different passwords. I would prefer not to do this.
3. Completely change how Nault is doing the authentication:
3a. If they use the address book first, ask them to set a password. If later importing a seed, make them type in that password so Nault can encrypt the seed using the same password (can't ever save the password)
3b. If they import the seed first, ask to set a password as usual. At the same time encrypt the address book using the same password (even if empty).
3c. When unlocking the wallet it will either decrypt the address book, seed or both depending on what's available. Using the Ledger would be unaffected. However, not sure how to solve the case when the user imports a wallet from a file that has a different password than the already encrypted address book. Maybe not possible to solve. In that case, option 3 is also out of the picture.
4. Do not do anything because it's more user friendly. Accept the risk that someone accessing your computer and fiddling with the address book. If you are afraid of this, export the address book to a USB flash drive and import it every time you need it.

**Comment by filipesmedeiros** [comment]
Can you make the address password optional? Is the possible? Then, using option 2. would be fine, because the user actively opted into tracking 2 passwords.

**Comment by Behind100proxies** [comment]
I think atleast a disclaimer stating that the adressbook is not protected and can get altered at any time would help. 
I think most users, like me are under the impression that your adressbook is relatively safe.

Or add a "last change on dd-mmmm-yyyy" field in the adress book that tracks changes so that when you are preparing a transfer you can notice the fact that something was altered recently

**Comment by filipesmedeiros** [comment]
I like both of those options. Although the "last change date" would have to be stored locally so a smart enough attacker would be able to change it, right?

**Comment by aleksre** [comment]
If an "attacker" has full access to your computer, wouldn't you have much bigger problems than them changing the address book in Nault? How about, you know, locking your computer? 

Opting into address book encryption might be possible, but is it actually useful? I don't really see what the use case is. It's the _device_ (or user account) that needs to be protected from tampering, not the address book itself.

**Comment by filipesmedeiros** [comment]
@aleksre agreed. Just another layer. Opt in for me would be the best option.
