### ISSUE TITLE
Add OpenAlias Support

### ISSUE THREAD

**Issue by ppfeister** [Nault/Nault#414]
**Is your feature request related to a problem? Please describe.**
Long hexadecimal wallet addresses are hard to remember, and they are _very_ unfriendly to the average user. This presents a huge barrier to wider adoption. Other currencies have tried to resolve this through new blockchain-based TLDs (ENS Domains, Unstoppable Domains, etc.), but those all rely on smart contracts - a feature Nano lacks. These new TLDs are also not supported by ICANN, meaning none of the standard DNS providers will actually resolve them.

**Describe the solution you'd like**
[OpenAlias](https://openalias.org/) is the perfect solution, at least until we find something better. The standard calls for a TXT record to be defined on a domain using any of the traditional TLDs (like .com). DNSSEC is encouraged by the standard to better prevent MITM attacks, but it is up to the individual implementation to require it or not. Formatted as following...
```
"oa1:nano recipient_address=nano_1111111111111111111111111111111111111111111111111111hifc8npp; recipient_name=John Doe;"
```
Once this record is defined, a user should be able to simply send Nano to example.com, instead of nano_111...npp. I encourage you to read the full write up on OpenAlias's homepage (https://openalias.org/).

**Describe alternatives you've considered**
The traditional solutions (i.e. decentralized name servers) either won't work with Nano, or would be very impractical. See first paragraph.

**Additional context**
No additional context at this time.

**Comment by Joohansson** [comment]
It's a nice idea but I'm not convinced this can be made secure enough considered Nault is a client-side application and DNS lookup would use whatever DNS that the computer is using (I think). Say you get something malicious in the machine that intercepts any DNS lookup and returns a fake address. How to prevent that?

**Comment by ppfeister** [comment]
That's definitely a concern, but I don't believe it would be an issue if implemented correctly. Standard DNS is definitely vulnerable to man-in-the-middle attacks (as you mentioned), but if DNSSEC or DoT (DNS over TLS) is used, it _should_ mitigate that.

After all, TLS is what we use for just about all of our other internet traffic, and it's proven very secure on that front. A lot of web browsers are starting to ship with DoT enabled by default for normal web traffic, as well (which is a good thing).

---
I'd like to see this enhancement use DoT by default, but I don't know how feasible that is just yet for Nault (I'd like to look more into that eventually). When it comes to DNSSEC, Nault has two possible solutions -
( a ) Outright require DNSSEC, and don't allow transactions to domains without it properly configured, or
( b ) Warn the user that they should verify the address if DNSSEC is not properly configured on that domain.
Either way, the threat can be mitigated here as well (again, in theory).

---
Thoughts?
I'd like to hear other people's thoughts on this too. I'm actually playing around with a [possible] PR for [Natrium](https://github.com/appditto/natrium_wallet_flutter) that would do just this, but it's a bit of a pain to do in Dart.

**Comment by Joohansson** [comment]
You are always welcome to make a PR but as you say, probably best to have some more input first. At least I can't think of any other reason not to support this. It's a completely optional feature to utilize.

**Comment by BitDesert** [comment]
As Nault is also a browser app it's not possible to query your local DNS server for the TXT record and you would have to query a third-party DNS server via HTTPS.
Why is everything handled by TXT records and not by a dedicated backend like OpenCAP https://github.com/opencap/protocol ?
It could introduce weird issues while the DNS changed propagate through the network.

**Comment by ppfeister** [comment]
I wasn't familiar with OpenCAP, but at first glance it seems to just overcomplicate things. What's the advantage with using OpenCAP's method over that of OpenAlias? It seems (again, only at first glance) to have a much higher barrier to entry (in regards to technical knowledge and physical equipment).

Let's take a small, local business. They probably have email on their own domain, and maybe a small website. But they aren't hosting any of that locally - they're paying some cheap shared host to do it for them. They can't run server applications like that (or they won't know how), but they can certainly add a TXT record on their domain if guided. No extra cost whatsoever, unlike the extra compute time for your new server.

---
In regards to your other point... OpenAlias would indeed be using a third-party DNS server, but none that you don't already use. As long as you're using any normal ICANN supported TLD, then your records will be usable to anyone, anywhere, no matter the DNS provider (as long as it's legitimate, of course).

I do kind of agree with you about the propagation times - I think that's up to individual implementation though. A low TTL should be more than enough to avoid issues, so as long as you're not behind some sort of outage or delays, it might just take a couple minutes with a standard TTL. More sensitive people/businesses can of course make it even shorter, too, but realistically people shouldn't be changing this on a daily basis, right?

---
(to be clear, these have all been very good questions)

**Comment by Joohansson** [comment]
Regarding the propagation time. The issue is not really how long it takes, it's that the user must be aware that what their DNS resolves might not be what the person who sends the funds might see it. This means if they change their nano address, they must make sure the old one works for enough overlapping time, say 48h or whatever their TTL is. It's not a big issue but it could result in loss of funds if they are not aware of this limitation.

**Comment by keerifox** [comment]
Unstoppable Name Service (UNS) support would be really nice to have, if I had zero concerns for the potential security implications of introducing a third party library I would have submitted a PR by now

https://github.com/unstoppabledomains/resolution

**Comment by ppfeister** [comment]
I was working on a PR for this not too long ago, but had to stop for a bit because of other "real world" obligations.

The thing that draws me to OpenAlias over Unstoppable is that they are already supported by all providers, as opposed to requiring the use of additional special ones. But that being said, I see absolutely zero reason why both can't be implemented at the same time.

I'd be on board with added Unstoppable compatibility.

**Edit:** Of course this is still limited by my original post, in that anybody wanting to use Unstoppable domains would need to use a secondary currency (such as ETH) to set it up. Not entirely contained on Nano, but usable still.

**Comment by zQueal** [comment]
> As Nault is also a browser app it's not possible to query your local DNS server for the TXT record and you would have to query a third-party DNS server via HTTPS. Why is everything handled by TXT records and not by a dedicated backend like OpenCAP https://github.com/opencap/protocol ? It could introduce weird issues while the DNS changed propagate through the network.

Frankly, after wrangling with OpenCap for the better part of two hours to get it installed and setup, I've given up... The project is old, and seems to be pretty much abandoned. The current readme is tantamount to gobbledygook, and I was unable to get it up and running on a test server in any capacity despite it seeming pretty straightforward.

OpenAlias was about the same. The project seems all but abandoned. The premise is sound, and it works perfectly fine, but there's been no movement on the project in months.

Unstoppable domains are great in theory, but I can't help but think they're a ploy at getting rich quick. The average domain prices;

|Chars|$|
|:--|:--|
|6|$200|
|5|$700|
|4|$2100|
|3|$4400|
|2|???|
|1|???|

These don't seem to be domain names which can even be registered with DNS, so they're effectively non-functioning and only work to serve as web3 addresses. The names are expensive seemingly singularly because they _can_ be expensive as low character `name.tld` are a commodity. Effectively for the same reason why NFT's are expensive. Especially so with them being "lifetime" leases. You don't own these domains. They can __only__ be used with this one service, and you're forking over an entire fortune for them. Doesn't seem right. Not to mention if any of those domains ever go live on DNS, it's going to cause a hell of a lot of confusion.

**Comment by ppfeister** [comment]
Closing due to #587
