### ISSUE TITLE
Incorrect transaction date

### ISSUE THREAD

**Issue by Compunologist** [Nault/Nault#63]
Transaction dates are often not displayed correctly at Nault startup. [Reload] or [Force Reload] will sometimes correct the date column but will also inconsistently revert dates back to the wrong ones:

![Wrong timestamp](https://user-images.githubusercontent.com/20874837/87871659-62f7f380-c9b2-11ea-922d-7de3ed51d105.jpg)
Comparison of transaction dates, incorrect data encircled in red on the left and the correct dates are visible on the right.

Only transactions on or before 2020-05-10 (May 10th) seem to be affected, these transactions are all incorrectly time-stamped 2020-05-10. I have tested 6 different accounts and 4 different wallets (including one Nano Ledger X) on 3 different systems, all displaying the same behavior.

(Nano Desktop v1.5.2 on Windows 10 Home v2004, Windows 10 Pro v1909 and Linux Mint v20 (Cinnamon) )

**Comment by aleksre** [comment]
Thanks for your report. I see the same behavior. After some digging it seems like the timestamps that come from the server are actually incorrect. If your server is set to random that would explain the inconsistencies. I see a lot of May 2020 dates coming from MyNanoNinja. I also see alot of 0 timestamps (01-01-1970) from both Nanos.cc and NanoCrawler which we should probably handle as 'N/A'. Nanex.cc seems to be the most accurate. 

Does it fix your problem if you set your server config to Nanex.cc instead of random?

**Comment by Compunologist** [comment]
@aleksre Thank you for investigation and pointing me in the right direction. My server was indeed set to "Random" hence the inconsistencies. I tried all servers from the list and Nanos.cc, Nanex.cc and NanoCrawler all return the correct dates. I can only reproduce the wrong May 10th transaction dates when using "My Nano Ninja". I have seen the 0 timestamp (01-01-1970) several times in the Nanocrawler block explorer but have not encountered it yet on my systems.

**Comment by BitDesert** [comment]
10th May is probably the date when I set up the new node and did a full sync. I don't know if there is currently a proper way of importing dates to a node.
Maybe we should clarify this on the frontend as well?

**Comment by BitDesert** [comment]
Won't fix, that's the only date we know. Adding another source for dates is probably overkill.
The node owner could fix the dates from a backup.
